### ISSUE TITLE
Azure Government Support

### ISSUE THREAD

**Issue by shmack01** [microsoft/vscode-azurecognitivesearch#15]
This is a great extension, but it doesn't pick up the current Azure Account environment setting, such as APIM, Function Apps, etc. In VS Code, when you are signed in with the "Azure Account" extension for Azure Government the following error occurs:

Error: The access token has been obtained for wrong audience or resource 'https://management.core.windows.net/".  It should exactly match with one of the allowed audiences 'https://management.core.usgovclientapi.net"....

![image](https://user-images.githubusercontent.com/46727041/118715594-cc72a980-b7f1-11eb-9739-08f34221a4d6.png)

**Comment by dereklegenzoff** [comment]
Hi @shmack01 - thanks for reporting this. 

I've attached an updated version of the extension ([gov-friendly-vscode-azurecognitivesearch.zip](https://github.com/microsoft/vscode-azurecognitivesearch/files/6517957/gov-friendly-vscode-azurecognitivesearch.zip)) for you with a small tweak that will make this work for gov cloud. To install it:
1.	Download the file and open VS Code 
2.	Unzip the folder
3.	Press Cntrl + Shift + P to open up the command palette 
4.	Type "Install from VSIX" and select that command. Navigate to the VSIX file and select it

After installing the extension, please make sure the settings of the Azure Account extension look like this:
![image](https://user-images.githubusercontent.com/19762985/119028447-52aaff00-b95c-11eb-89b2-8e61ee100215.png)

And that the settings for the Azure Cognitive Seach extension (Settings -> Extensions -> Azure Cognitive Search) look like this:
![image](https://user-images.githubusercontent.com/19762985/119028504-635b7500-b95c-11eb-9fe7-7705d3600885.png)


Could you let me know if that works for you?

**Comment by dereklegenzoff** [comment]
In case you're wondering, the updated extension I attached changes the value of this [line](https://github.com/microsoft/vscode-azurecognitivesearch/blob/master/src/SimpleSearchClient.ts#L186) to point to `search.azure.us` from `search.windows.net`. 

I will try to get an update in so this is a better experience and doesn't require a separate version of the extension.

**Comment by shmack01** [comment]
Works perfectly! Thank you for adding the update for the  US Gov endpoint.

**Comment by dereklegenzoff** [comment]
Awesome, glad to hear it :)
